### ISSUE TITLE
Nettsiden kan krasjer når du endre idiot sin type

### ISSUE THREAD

**Issue by IceWafflez** [Madelelo/bakebok#25]
sjekk typen til idiot på app.js før funksjonen som endrer data, og endre den tilbake og legg til en alert("")

**Comment by IceWafflez** [comment]
kunne aldri ha skjedd med bakkacoin

**Comment by Madelelo** [comment]
<img width="1015" alt="Screen Shot 2022-05-10 at 19 39 41" src="https://user-images.githubusercontent.com/6739072/167689486-08c74e5b-773a-4fa0-aa5b-785f2dcfe41a.png">
